sudo: required
dist: trusty

language: go

go:
  - 1.12.0

os:
  - linux

env:
  matrix:
    - TARGETS="test"
    - TARGETS="build"

before_install:
  - umask 022
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/
  - cd $HOME/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/

install:
  - true

script:
  - make $TARGETS

